# Generated by Django 2.2 on 2019-04-11 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('store', models.CharField(max_length=50)),
                ('brief_introduction', models.CharField(max_length=400)),
                ('price', models.FloatField(blank=True, null=True)),
                ('variety', models.CharField(max_length=100)),
                ('product_id', models.BigIntegerField()),
                ('authenticate_moder', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('crawl_time_stamp', models.IntegerField()),
                ('crawl_time', models.DateTimeField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_info',
                'managed': False,
            },
        ),
    ]
