# Generated by Django 2.2 on 2019-04-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdPrice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinfo',
            options={'verbose_name': 'Scrapy爬取的京东商品信息', 'verbose_name_plural': 'Scrapy爬取的京东商品信息'},
        ),
    ]
