# Generated by Django 2.2 on 2019-04-11 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdPrice', '0002_auto_20190411_0415'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsinfo',
            options={'managed': False, 'verbose_name': 'Scrapy爬取的京东商品信息', 'verbose_name_plural': 'Scrapy爬取的京东商品信息'},
        ),
    ]
