# Generated by Django 2.2 on 2019-04-11 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdPrice', '0004_addressinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddressInfo',
        ),
    ]
