# Generated by Django 2.2 on 2019-05-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdPrice', '0005_delete_addressinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=100)),
                ('passwd_encode', models.Field()),
                ('email', models.Field(blank=True, null=True)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Django用户账号信息',
                'verbose_name_plural': 'Django用户账号信息',
                'db_table': 'users_info',
                'managed': False,
            },
        ),
    ]
